# Generated by Django 5.1.7 on 2025-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingcontroller',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
