# Generated by Django 5.1.7 on 2025-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gamingcontroller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingcontroller',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
