# Generated by Django 5.1.7 on 2025-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamingcontroller',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
