services:
  - type: web
    name: controlx
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn NOME_DO_PROJETO.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: NOME_DO_PROJETO.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False